# Generated by Django 5.0 on 2023-12-17 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='usermodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=30)),
                ('Bhk', models.IntegerField()),
                ('bathroom', models.IntegerField()),
                ('balcony', models.CharField(max_length=5)),
                ('playground', models.CharField(max_length=5)),
                ('landmark', models.CharField(max_length=50)),
                ('price_range', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Userinput',
        ),
    ]
